engines:
  checkstyle:
    enabled: true
    channel: "beta"

exclude_paths:
  - "docs/*"
  - "misc/*"
  - "gradle/*"
  - "demo/*"

ratings:
  paths:
  - "core/src/main/java/edu/mines/jtk/util/**.java"