language: java

branches:
  only:
    - master

install: true

jdk: 
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

script: ./gradlew build -x :core:signArchives

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_install:
  - "echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-"

env:
  global:
    # Coverity Scan token
    secure: "jJirBkZOyJ8KuYXMbjUpKem2FGaCsLBq7roP9oHs5mz8wIKENGB3i7pBe5USVLCwVAuqJ+TPjbfSo4nSnCIf5mLdJoNnyrq8FAYhSRzA/zl4COW6eN0Of9dgCOzcOriPY9rXUVbIapWoMogntnAS6MpmbiSxQCsq99VsIHq3TYk="

script:
  - autoreconf -f -i
  - ./configure --enable-tests
  - make -j2
  - make check

addons:
  coverity_scan:
    project:
      name: sionescu/libfixposix
    build_command_prepend: autoreconf -f -i && ./configure --enable-tests
    build_command: make -j4
    branch_pattern: coverity
    notification_email: sionescu@cddr.org


env:
  global:
   # Coverity token
   - secure: "SNKJAyFHhLyds1iQBJZ/0rZzougnOIcRd7cooSyhwHusZ/0h47T4FZ8veTtvSw1kNRfN/ciQWsxl9nEWfKH+OBCyCozKCVhhbWgm0PNyOZGM1bjftJQkr18+KffnlUVejLnY26J/aHunyC4xsQrQn9nOum8G3x/BQOrh76V8ET5x50n0cUBJlKyxZDXwOcheE2p5QCoHHv5VjL0mns3lLd8aA4mkDSCb+sHL0yxSH1ON5H2yFMfzcYsv5N7i8wI445/V2R01BrvZZdl93WxgSArCIMG3psI/zXhYB2XH6K7KVVisO00r60gulMu/VMp7GmWAVTrk2CXa4e5d1SYGfptKgA0rModnX4BFd59huP8V1wXMDKYNulVnE5r01tmKMT8+tREnMwM8JHN+NLfE0BjPyPFcuPU1JwsACYoz2dLqMhEBWRi2IDgs4UZ3YT2na/cPAG57N4OWnc8dBlAB53b6qtZmGqtyrSvkmnudQR9vjPJA3070zwovLISyiQ49tCvOFGiGtzBp0U+1Bq/28ahxbGKigsl6zDa00wjRxjvraUMYbRgQ86Wfs1UnWsi5IX+8dcq7rjP4ZHLrvU0inHuyzFyV/O7Yw/ADZ+E5HcOwCtenZvXg546Z7n2/ujHQGmYXEBuNIhpyEjDom2SorXdzMF+7FwgpnQuBo/fnzlM="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "chrisengelsma/jtk"
    notification_email: chris.engelsma@gmail.com
    build_command:  ./gradlew build -x :core:signArchives
    branch_pattern: coverity_scan